export const _errors = {
  required: 'Campo obligatorio',
  minLength: 'Texto muy corto',
  maxLength: 'Texto muy largo',
  regex: 'Caracter inválido',
  email: 'Email inválido',
  oneLowerCase: 'Debe incluir al menos una letra minúscula',
  oneUpperCase: 'Debe incluir al menos una letra mayúscula',
  oneNumber: 'Debe incluir al menos un número',
  oneSpecialCharacter: 'Debe incluir al menos un caracter especial',
  min: 'Debe ser mayor o igual a',
  max: 'Debe ser inferior o igual a',
  decimals: 'Número entero con máximo 2 decimales',
  iva: 'Si IVA es diferente a 0, Impoconsumo debe ser 0',
  impoconsumo: 'Si Impoconsumo es diferente a 0, IVA debe ser 0',
};
